module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-unstable
cabal-file: project.cabal
hidden-packages: monads-tf
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- Setup.hs
- src/main/Main.hs
