#!/bin/bash -xe

#
# EKB FIXME remove more unnecessary files (or just copy a whitelist?)
#

cd $(dirname $0)/..
s=$(pwd)
t=$(mktemp -dt data-analysis-demo.XXXXXX)

git clone . $t/skel
cd $t/skel

# EKB TODO perhaps would be better to not include these files in the repo to start with
#   (move the import wizard to a separate repo, etc)
rm -rf .git scripts src/FP/ImportWizard data/import-wizard static/flot/examples test src/UserModel.hs
rmdir src/FP
test -d data && rmdir data

perl -i -pe 's/DataAnalysis.Application.Types.Stock/UserModel/' src/main/Main.hs src/User*.hs src/DataAnalysis/Application/Import.hs

git init
git add --all
git commit -m "Data analysis skeleton"

mkdir -p $s/data/import-wizard
tar czf $s/data/import-wizard/skel.tgz .

cd $s
rm -rf $t
